language: python
dist: xenial
python:
    - "3.7"
    - "pypy3"
matrix:
    allow_failures:
        - python: "pypy3"
before_install:
    - pip install poetry
install:
    - poetry install -v
    - pip install tox-travis
script:
    - tox
