language: python
dist: xenial
python:
    - "3.6"
    - "3.7"
    - "pypy3"
matrix:
    allow_failures:
        - python: "pypy3"
addons:
    apt:
        packages:
            - libopenblas-dev
before_install:
    - pip install poetry
install:
    - poetry install -v
    - pip install tox-travis
script:
    - tox
